server:
  port: 9001
  
 #jsp
spring:
  devtools:
    livereload:
      enabled: true
 
 #mysql
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mindata.csezciyfulkw.ap-northeast-2.rds.amazonaws.com:3306/haemins?serverTimezone=Asia/Seoul
    username: haemin
    password: haemin1964+
    
#mybatis
mybatis:
  type-aliases-package: data.*
  mapper-locations:
  - /mappers/**/*.xml